# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Prismarine"
license = "BSD-3-Clause"
languageCode = "en"
licenselink = "https://github.com/doamatto/personal-site/blob/master/LICENSE"
description = "The redesign of doamatto.xyz"
homepage = "https://doamatto.xyz/"
tags = []
features = []
min_version = "0.41.0"
canonifyURLs = true

[permalinks]
  posts = "/posts/:title/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
  [languages.fr]
    contentDir = "content/fr"
    languageName = "Français"
    weight = 20

[author]
  name = "doamatto"
  homepage = "https://doamatto.xyz"

[params]
  favicon = "assets/logo.svg"
  logo = "assets/logo.svg"