baseURL = "https://doamatto-site-git-fix-scss-loading.doamatto.vercel.app"
languageCode = "en-uk"
title = "doamatto"

canonifyURLs = true

[Permalinks]
  posts = "/posts/:filename/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
  [languages.fr]
    contentDir = "content/fr"
    languageName = "Français"
    weight = 20

[author]
  name = "doamatto"
  homepage = "https://doamatto.xyz"

[Params]
  favicon = "assets/logo.svg"
  logo = "assets/logo.svg"