name: "CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1.4.2
      
    - name: Install Deps
      run: |
        yarn
        yarn global add gulp-cli
        yarn global add hugo-extended
    - name: Gulp... Yea.
      run: gulp
