name: "Markdown Linting"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: posts/*
